# -*- coding: utf-8 -*-
"""Sentence Similarity Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyHVAAG6lEecHpnH5j6q-GzrXTYSCeI1
"""

!pip install transformers torch

from transformers import pipeline
generator=pipeline("text-generation",model="gpt2")
prompt="Deep Learning in Data Science"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])

from sentence_transformers import SentenceTransformer,util
model=SentenceTransformer('all-MiniLM-L6-v2')
text1=input("Enter Text 1: ")
text2=input("Enter Text 2: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
Similarity=util.cos_sim(embedding1, embedding2)
print("\n Similarity Score:",round(float(Similarity), 2))
if Similarity > 0.75:
   print("Similarity Level: High")
elif Similarity > 0.4:
   print("Similarity Level: Medium")
else:
    print("Similarity Level: Low")