# -*- coding: utf-8 -*-
"""Text Generation Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maMQ5RorfLIJ0nM3dIhe3SOXfJ5I0yIP
"""

!pip install transformers torch

from  transformers import pipeline
generator = pipeline("text-generation" , model = "gpt2")
prompt = "Artificial Intelligence in Finanance will"
result = generator(prompt , max_length = 50 , num_return_sequences = 1)
print("AI generated text:")
print(result[0]['generated_text'])